- name: Download and extract prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}-rc.0/prometheus-{{ version }}-rc.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: copy prometheus service
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: start prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true